deploy install

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -171,41 +171,40 @@ install:
 ###
 # Building OCCT
 ###
-#    - curl -o occt.tgz "http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=b00770133187b83761e651df50051b2fa3433858;sf=tgz"
-#    - gunzip occt.tgz
-#    - tar xf occt.tar
-#    - rm occt.tar
-#    - cd occt-b007701
+    - cd ../..
+    - curl -o occt.tgz "http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=b00770133187b83761e651df50051b2fa3433858;sf=tgz"
+    - gunzip occt.tgz
+    - tar xf occt.tar
+    - rm occt.tar
+    - cd occt-b007701
+
 #    - mkdir build
 #    - cd build
 #    - cmake .. -DUSE_VTK:BOOL=OFF
 
-#    - cd ../..
-#    - mkdir occt-b007701
-#    - cd occt-b007701
-#    - curl -O -L "https://github.com/sasobadovinac/FreeCAD/releases/download/0.17/build_occt.tar.gz"
-#    - tar -zxf build_occt.tar.gz
-#    - ls
-#    - cd build
-#    - sudo make install
+    - curl -O -L "https://github.com/sasobadovinac/FreeCAD/releases/download/0.17/build_occt.tar.gz"
+    - tar -zxf build_occt.tar.gz
+    - ls
+    - cd build
+    - sudo make install
 
 ###
 # Building Netgen
 ###
 
-#    - cd ../..
-#    - git clone https://github.com/vejmarie/Netgen
-#    - cd Netgen/netgen-5.3.1
-#    - ./configure --with-tcl=/usr/lib/tcl8.5 --with-tk=/usr/lib/tk8.5  --enable-occ  --enable-shared --enable-nglib CXXFLAGS="-DNGLIB_EXPORTS -std=gnu++11"
-#    - make -j 2
-#    - sudo make install
-#    - cd ../..
-#    - sudo cp -rf Netgen/netgen-5.3.1 /usr/share/netgen
+    - cd ../..
+    - git clone https://github.com/vejmarie/Netgen
+    - cd Netgen/netgen-5.3.1
+    - ./configure --with-tcl=/usr/lib/tcl8.5 --with-tk=/usr/lib/tk8.5  --enable-occ  --enable-shared --enable-nglib CXXFLAGS="-DNGLIB_EXPORTS -std=gnu++11"
+    - make -j 2
+    - sudo make install
+    - cd ../..
+    - sudo cp -rf Netgen/netgen-5.3.1 /usr/share/netgen
 
 ####
 #  Build FreeCAD with cmake options set above for each platform
 ###
-#    - mkdir build && cd build && cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
+    - mkdir build && cd build && cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
 
 script:
 ####
@@ -216,37 +215,37 @@ script:
 #    - tar -zcf build_occt.tar.gz build
 #    - ls
 
-#    - sudo make -j2 install
-#    - ${INSTALLED_APP_PATH} --run-test 0
-#    - ${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log &
-#    - sleep 10 && pkill FreeCAD
-#    - cat /tmp/FreeCAD_installed.log
-#    - grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )
+    - sudo make -j2 install
+    - ${INSTALLED_APP_PATH} --run-test 0
+    - ${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log &
+    - sleep 10 && pkill FreeCAD
+    - cat /tmp/FreeCAD_installed.log
+    - grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )
 
-#after_success:
+after_success:
 ####
 #  Package and deploy the build to GitHub.  This will only run for builds on
 #  master (i.e. pull requests are only built and tested but not deployed).
 #
 #  GH_TOKEN must be set in order to deploy releases to GitHub
 ##
-#- |
-#  if [ "${TRAVIS_OS_NAME}" == "osx" -a "${TRAVIS_PULL_REQUEST}" == "false" ]; then
-#     brew install jq node && npm install -g appdmg
-#     export VSN=$(python ${TRAVIS_BUILD_DIR}/src/Tools/ArchiveNameFromVersionHeader.py ${TRAVIS_BUILD_DIR}/build/src/Build/Version.h)
-#    - export DEPLOYMENT_ARCHIVE=build_VTK-7.0.0.tar.gz
-#     appdmg ${TRAVIS_BUILD_DIR}/src/MacAppBundle/DiskImage/layout.json "${DEPLOYMENT_ARCHIVE}"
-#    - deployContext=$(create_helper_context repo=${TRAVIS_REPO_SLUG} auth_token=${GH_TOKEN} release=${DEPLOY_RELEASE})
-#    - gitHub_deploy_asset_to_release_named $deployContext ${DEPLOYMENT_ARCHIVE} replace
-#     gitHub_prune_assets_for_release_named $deployContext "-OSX-" 3
-#  fi
+- |
+  if [ "${TRAVIS_OS_NAME}" == "osx" -a "${TRAVIS_PULL_REQUEST}" == "false" ]; then
+     brew install jq node && npm install -g appdmg
+     export VSN=$(python ${TRAVIS_BUILD_DIR}/src/Tools/ArchiveNameFromVersionHeader.py ${TRAVIS_BUILD_DIR}/build/src/Build/Version.h)
+     export DEPLOYMENT_ARCHIVE=${VSN}.dmg
+     appdmg ${TRAVIS_BUILD_DIR}/src/MacAppBundle/DiskImage/layout.json "${DEPLOYMENT_ARCHIVE}"
+     deployContext=$(create_helper_context repo=${TRAVIS_REPO_SLUG} auth_token=${GH_TOKEN} release=${DEPLOY_RELEASE})
+     gitHub_deploy_asset_to_release_named $deployContext ${DEPLOYMENT_ARCHIVE}
+     gitHub_prune_assets_for_release_named $deployContext "-OSX-" 3
+  fi
 
-deploy:
-  provider: releases
-  api_key: "${GH_TOKEN}"
-  file: "build_occt.tar.gz"
-  overwrite: true
-  skip_cleanup: true
-  on:
-    tags: false
-    all_branches: true
+#deploy:
+#  provider: releases
+#  api_key: "${GH_TOKEN}"
+#  file: "build_occt.tar.gz"
+#  overwrite: true
+#  skip_cleanup: true
+#  on:
+#    tags: false
+#    all_branches: true
